#base "mainmenuoverride_bg_customcolor.res"
#base "mainmenuoverride_bg_tf2.res"
#base "mainmenuoverride_bg.res"

#base "mainmenuoverride_rank.res"
#base "mainmenuoverride_tflogoimage.res"

"Resource/UI/MainMenuOverride.res" 
{
//"DashboardDimmer"
//{
//"tall" "4800"
//}
"Version"
{
	"ControlName" "Label"
	"fieldname" "Version"
	"xpos" "c-90"
	"ypos" "160"//"175"
	"zpos" "11"
	"wide" "180"
	"tall" "12"
	"visible" "1"
	"PaintBackgroundType" "0"
	"labeltext" "v1.5.0"
	"font" "m0refont12"
	"textalignment" "center"
	"fgcolor_override" "150 150 150 255"
}
"TF2Logo" 
{
	"ControlName" "EditablePanel"
	"fieldname" "TF2Logo"
	"xpos" "c-16"//25"
	"ypos" "80"//143"
	"zpos" "-11"
	"wide" "180"
	"tall" "32"
	"visible" "1"
	"PaintBackgroundType" "0"
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "f0"
		"autoResize" "0"
		"pinCorner" "3" // yes pinCorner is corner rounding
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "0"
		"use_proportional_insets" "1"
		"default" "1"
		"sound_depressed" ""
		"sound_released" ""
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		"image_drawcolor" "255 255 255 255"//"117 107 94 255"
		"image_armedcolor" "255 255 255 255"//"235 226 202 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "0"
			"ypos" "0"
			"zpos" "1"
			"wide" "32"
			"tall" "32"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
			"image"	"glyph_multiplayer"
			"drawcolor_override" "255 255 255 255"
		}
	}
}
"AstroHUD"
{
	"ControlName" "Label"
	"fieldname" "AstroHUD"
	"xpos" "c-90"
	"ypos" "120"
	"zpos" "11"
	"wide" "180"
	"tall" "32"
	"visible" "1"
	"labelText" "astrohud"
	"font" "Orbit32"
	"textalignment" "center"
	"fgcolor_override" "255 255 255 255"
}
"HudBy"
{
	"ControlName" "Label"
	"fieldname" "HudBy"
	"xpos" "c-90"
	"ypos" "160"
	"zpos" "11"
	"wide" "180"
	"tall" "12"
	"visible" "1"
	"PaintBackgroundType" "0"
	"labeltext" ""//"by wat the fricc and astroyed."
	"font" "m0refont12"
	"textalignment" "center"
	"fgcolor_override" "150 150 150 255"
}
"MainMenuOverride"
{
	"fieldName" "MainMenuOverride"
	"visible" "1"
	"enabled" "1"
	"xpos" "0"
	"ypos" "0"
	"zpos" "0"
	"wide" "f0"
	"tall" "480"
	"update_url" "store.steampowered.com/news/?filter=updates&appids=440"
	"blog_url" "www.teamfortress.com/"
	"button_x_offset" "-285"
	"button_y" "120"
	"button_y_delta" "5"
	"button_kv" 
	{
		"xpos" "0"
		"ypos" "150"
		"wide" "250"
		"tall" "26"
		"visible" "1"
		"SubButton" 
		{
			"ControlName" "CExImageButton"
			"fieldName" "SubButton"
			"xpos" "0"
			"ypos" "0"
			"wide" "250"
			"tall" "26"
			"autoResize" "0"
			"pinCorner" "3"
			"visible" "1"
			"enabled" "1"
			"tabPosition" "0"
			"textinsetx" "25"
			"use_proportional_insets" "1"
			"font" "HudFontSmallBold"
			"textAlignment" "north-west"
			"dulltext" "0"
			"brighttext" "0"
			"default" "1"
			"sound_depressed" "UI/buttonclick.wav"
			"sound_released" "UI/buttonclickrelease.wav"
			"border_default" "MainMenuButtonDefault"
			"border_armed" "MainMenuButtonArmed"
			"paintbackground" "0"
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			"image_drawcolor" "255 255 255 255"
			"image_armedcolor" "G_Highlight"
			"SubImage" 
			{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "6"
			"ypos" "6"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
			}
		}
	}
	"SaxxySettings" 
	{
		"xpos" "0"
		"ypos" "0"
		"zpos" "-101"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "0"
		"enabled" "0"
		"CameraFlashSettings" 
		{
			"visible" "0"
			"enabled" "0"
			"tileImage" "0"
			"scaleImage" "1"
			"zpos" "9"
		}
	}
}
"mouseoveritempanel" 
{
	"ControlName" "CItemModelPanel"
	"fieldName" "mouseoveritempanel"
	"xpos" "c-70"
	"ypos" "270"
	"zpos" "100"
	"wide" "300"
	"tall" "300"
	"visible" "0"
	"bgcolor_override" "0 0 0 0"
	"noitem_textcolor" "117 107 94 255"
	"PaintBackgroundType" "2"
	"paintborder" "1"
	"border" "MainMenuBGBorder"
	"text_ypos" "20"
	"text_center" "1"
	"model_hide" "1"
	"resize_to_text" "1"
	"padding_height" "15"
	"attriblabel" 
	{
		"font" "ItemFontAttribLarge"
		"xpos" "0"
		"ypos" "30"
		"zpos" "2"
		"wide" "140"
		"tall" "60"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"labelText" "%attriblist%"
		"textAlignment" "center"
		"fgcolor" "117 107 94 255"
		"centerwrap" "1"
	}
}
	"MainMenuBG" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "MainMenuBG"
		"xpos" "0"
		"ypos" "0"//70
		"zpos" "-20"
		//"wide" "177"
		//"wide" "180"
		"wide" "00"
		"tall" "480"//340
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		//"fillcolor" "yA_menuBG"
	}
	"MainMenuBGbottom" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "MainMenuBG"
		"xpos" "0"
		"ypos" "r60"//70
		"zpos" "-20"
		//"wide" "177"
		"wide" "f0"
		"tall" "480"//340
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"fillcolor" "panelBGtransparent"
	}
	"MainMenuBGLINE1" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "MainMenuBGLINE1"
		"xpos" "0"
		"ypos" "0"//70
		"zpos" "-19"
		"wide" "5"
		"tall" "480"//340
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "0"
		"enabled" "1"
		"fillcolor" "G_Highlight_menuline"
	}
	"MainMenuBGLINE2" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "MainMenuBGLINE2"
		"xpos" "175"
		"ypos" "0"//70
		"zpos" "-19"
		"wide" "5"
		"tall" "480"//340
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "0"
		"enabled" "1"
		"fillcolor" "G_Highlight_menuline"
	}
	// background was here
	"CustomBGInGame"
	{
		"ControlName" "EditablePanel"
		"fieldname" "CustomBGInGame"
		"xpos" "0"
		"ypos" "0"//r55"
		"zpos" "-199"
		"wide" "f0"
		"tall" "480"
		"visible" "1"
		"PaintBackgroundType" "2"
		"SubButton" 
		{
			"ControlName" "CExImageButton"
			"fieldName" "SubButton"
			"xpos" "0"
			"ypos" "0"
			"wide" "f0"
			"tall" "480"
			"autoResize" "0"
			"pinCorner" "3"
			"visible" "1"
			"enabled" "1"
			"tabPosition" "0"
			"textinsetx" "0"
			"use_proportional_insets" "1"
			"font" "m0refont14"
			"textAlignment" "north-west"
			"dulltext" "0"
			"brighttext" "0"
			"default" "1"
			"sound_depressed" ""
			"sound_released" ""
			"border_default" ""
			"border_armed" ""
			"paintbackground" "1"
			"defaultFgColor_override" "255 255 255 255"
			"armedFgColor_override" "G_Highlight"
			"depressedFgColor_override" "G_Highlight"
			"defaultBgcolor_override" "ya_pauseBG"
			"armedBgcolor_override" "ya_pauseBG"
			"depressedBgcolor_override" "ya_pauseBG"
			"bgcolor_override" "ya_pauseBG"
			"image_drawcolor" "117 107 94 255"
			"image_armedcolor" "235 226 202 255"
			
			"SubImage" 
			{
				"ControlName" "ImagePanel"
				"fieldName" "SubImage"
				"xpos" "9999"
				"ypos" "9999"
				"zpos" "1"
				"wide" "14"
				"tall" "14"
				"visible" "1"
				"enabled" "1"
				"scaleImage" "1"
			}
		}
	}
"MainMenuBGPanel" 
{
	"ControlName" "EditablePanel"
	"fieldName" "MainMenuBGPanel"
	"xpos" "9999"
	"ypos" "9999"
	"zpos" "-1"
	"wide" "260"
	"tall" "120"
	"visible" "1"
	"pinCorner" "0"
	"autoResize" "0"
	"PaintBackgroundType" "2"
	"border" "MainMenuBGBorder"
}

"TooltipPanel" 
{
	"ControlName" "EditablePanel"
	"fieldName" "TooltipPanel"
	"xpos" "0"
	"ypos" "0"
	"zpos" "1000"
	"wide" "150"
	"tall" "20"
	"visible" "0"
	"PaintBackgroundType" "2"
	"border" "MainMenuBGBorder"
	"TipSubLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TipSubLabel"
		"font" "HudFontSmall"
		"labelText" "%tipsubtext%"
		"textAlignment" "north"
		"xpos" "20"
		"ypos" "30"
		"zpos" "2"
		"wide" "250"
		"tall" "50"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"fgcolor_override" "117 107 94 255"
		"wrap" "1"
	}
	"TipLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TipLabel"
		"font" "HudFontSmallBold"
		"labelText" "%tiptext%"
		"textAlignment" "center"
		"xpos" "20"
		"ypos" "5"
		"zpos" "2"
		"wide" "140"
		"tall" "20"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"fgcolor_override" "235 226 202 255"
		"auto_wide_tocontents" "1"
	}
}

"WorkshopButton"
{
	"ControlName"	"CExImageButton"
	"fieldName"		"WorkshopButton"
	"xpos"			"4"
	"ypos"			"0"
	"zpos"			"2"
	"wide"			"12"
	"tall"			"12"
	"autoResize"	"0"
	"pinCorner"		"3"
	"visible"		"1"
	"enabled"		"1"
	"tabPosition"	"0"
	"labelText"		""
	"font"			"HudFontSmallBold"
	"textAlignment"	"center"
	"dulltext"		"0"
	"brighttext"	"0"
	"default"		"1"
	"Command"		"engine OpenSteamWorkshopDialog"
	"paintbackground" "0"

	"sound_depressed"	"UI/buttonclick.wav"
	"sound_released"	"UI/buttonclickrelease.wav"
	
	
	"image_drawcolor" "175 175 175 255"
	"image_armedcolor" "G_Highlight"
	
	"defaultFgColor_override" "255 255 255 255"
	"armedFgColor_override" "G_Highlight"
	"depressedFgColor_override" "G_Highlight"
	
	"pin_to_sibling" 							"ReplayButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	
	"SubImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"SubImage"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"12"
		"tall"			"12"
		"visible"		"1"
		"enabled"		"1"
		"image"			"glyph_steamworkshop"
		"scaleImage"	"1"
	}				
}

"FriendsContainer" 
{
	"ControlName" "EditablePanel"
	"fieldname" "FriendsContainer"
	"xpos" "0"
	"ypos" "c-160"//c-130"
	"zpos" "0"
	"wide" "150"
	"tall" "246" //260
	"visible" "1"
	"pinCorner" "0"
	"border" ""//MainMenuBGBorder"
	"bgcolor_override" "panelBGtransparent"
	"TitleLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TitleLabel"
		"font" "HudFontSmallBold"
		"labelText" "#TF_Competitive_Friends"
		"textAlignment" "center"
		"xpos" "12"
		"ypos" "9990"
		"zpos" "505"
		"wide" "f0"
		"tall" "30"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "0"
		"enabled" "01"
		"textinsetx" "0"
		"fgcolor_override" "255 255 255 255"
	}
	"InnerShadow" 
	{
		"ControlName" "EditablePanel"
		"fieldname" "InnerShadow"
		"xpos" "cs-0.5"
		"ypos" "rs1-10"
		"zpos" "501"
		"wide" "f20"
		"tall" "110"
		"visible" "0"
		"PaintBackgroundType" "0"
		"proportionaltoparent" "1"
		"mouseinputenabled" "0"
		"paintborder" "0"
		"border" "InnerShadowBorder"
	}
	"SteamFriendsList" 
	{
		"ControlName" "CSteamFriendsListPanel"
		"fieldname" "SteamFriendsList"
		"xpos" "5"
		"ypos" "10"
		"zpos" "500"
		"wide" "f10"
		"tall" "f20" //238
		"visible" "1"
		"proportionaltoparent" "1"
		"columns_count" "1"
		"inset_x" "10"
		"inset_y" "5"
		"row_gap" "5"
		"column_gap" "20"
		"restrict_width" "0"
		"friendpanel_kv" 
		{
			"wide" "100"
			"tall" "20"
		}
		"ScrollBar" 
		{
			"ControlName" "ScrollBar"
			"FieldName" "ScrollBar"
			"xpos" "rs1-1"
			"ypos" "0"
			"tall" "f0"
			"wide" "5"
			"zpos" "1000"
			"nobuttons" "1"
			"proportionaltoparent" "1"
			"Slider" 
			{
				"fgcolor_override" "TanDark"
			}
			"UpButton" 
			{
				"ControlName" "Button"
				"FieldName" "UpButton"
				"visible" "0"
			}
			"DownButton" 
			{
				"ControlName" "Button"
				"FieldName" "DownButton"
				"visible" "0"
			}
		}
	}
	"BelowDarken" 
	{
		"ControlName" "EditablePanel"
		"fieldname" "BelowDarken"
		"xpos" "cs-0.5"
		"ypos" "rs1-10"
		"zpos" "499"
		"wide" "f20"
		"tall" "0"
		"visible" "0"
		"PaintBackgroundType" "0"
		"proportionaltoparent" "1"
		"mouseinputenabled" "0"
		"bgcolor_override" "0 0 0 100"
	}
}
"CompetitiveAccessInfoPanel" 
{
	"ControlName" "CCompetitiveAccessInfoPanel"
	"fieldName" "CompetitiveAccessInfoPanel"
	"xpos" "cs-0.5"
	"ypos" "cs-0.5"
	"zpos" "1000"
	"wide" "f0"
	"tall" "f0"
	"visible" "0"
}
"ReplayButton" 
{
	"ControlName" "CExImageButton"
	"fieldName" "ReplayButton"
	"xpos" "4"
	"ypos" "0"
	"zpos" "2"
	"wide" "12"
	"tall" "12"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"tabPosition" "0"
	"labelText" ""
	"font" "TF2Glyphs25"
	"textAlignment" "north"
	"dulltext" "0"
	"brighttext" "0"
	"default" "1"
	"Command" "engine replay_reloadbrowser"
	"sound_depressed" "UI/buttonclick.wav"
	"sound_released" "UI/buttonclickrelease.wav"
	"border_default" ""
	"border_armed" ""
	"paintbackground" "0"
	"PaintBackgroundType" "0"
	
	"image_drawcolor" "175 175 175 255"
	"image_armedcolor" "G_Highlight"
	
	"defaultFgColor_override" "255 255 255 255"
	"armedFgColor_override" "G_Highlight"
	"depressedFgColor_override" "G_Highlight"
	
	"pin_to_sibling" 							"GeneralStoreButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "0"
		"ypos" "0"
		"zpos" "1"
		"wide" "12"
		"tall" "12"
		"visible" "1"
		"enabled" "1"
		"image" "glyph_tv"
		"scaleImage" "1"
	}
}

"GeneralStoreButton" 
{
	"ControlName" "CExImageButton"
	"fieldName" "GeneralStoreButton"
	"xpos" "r52"
	"ypos" "r44"
	"zpos" "1"
	"wide" "12"
	"tall" "12"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"tabPosition" "0"
	"labelText" ""
	"font" "TF2Glyphs25"
	"textAlignment" "north"
	"dulltext" "0"
	"brighttext" "0"
	"default" "1"
	"Command" "engine open_store"
	"sound_depressed" "UI/buttonclick.wav"
	"sound_released" "UI/buttonclickrelease.wav"
	"border_default" ""
	"border_armed" ""
	"paintbackground" "0"
	"PaintBackgroundType" "0"
	"image_drawcolor" "175 175 175 255"
	"image_armedcolor" "G_Highlight"
	"defaultBgColor_override" 	"0 0 0 0"
	"armedBgColor_override" 	"0 0 0 0"
	"depressedBgColor_override" "0 0 0 0"
	
	
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "0"
		"ypos" "0"
		"zpos" "1"
		"wide" "12"
		"tall" "12"
		"visible" "1"
		"enabled" "1"
		"image" "glyph_store"
		"scaleImage" "1"
	}
}

// items
"CharacterSetupButton" 
{
	"ControlName" "EditablePanel"
	"fieldname" "CharacterSetupButton"
	"xpos" "0"
	"ypos" "r60"//203"
	"zpos" "11"
	"wide" "60"
	"tall" "60"
	"visible" "1"
	"PaintBackgroundType" "2"
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "0"
		"use_proportional_insets" "1"
		"font" "m0refont20"
		"textAlignment" "north-west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		
		"image_drawcolor" "175 175 175 255"
		"image_armedcolor" "253 253 253 255"
		
		"labelText" ""
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "10"
			"ypos" "10"
			"zpos" "1"
			"wide" "40"
			"tall" "40"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
			"image"			"glyph_items"
		}
	}
}

"ResumeGameButton" 
{
"ControlName" "EditablePanel"
"fieldname" "ResumeGameButton"
"xpos" "9940"
"ypos" "105"
"zpos" "11"
"wide" "140"
"tall" "20"
"visible" "1"
"PaintBackgroundType" "0"
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "0"
		"enabled" "0"
		"tabPosition" "0"
		"textinsetx" "0"
		"use_proportional_insets" "1"
		"font" "m0refont20"
		"textAlignment" "north-west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		"defaultFgColor_override" "255 255 255 255"
		"armedFgColor_override" "G_Highlight"
		"depressedFgColor_override" "G_Highlight"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "235 226 202 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "9999"
			"ypos" "9999"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
		}
	}
}

//
// pause menu stuff
//

"MutePlayersButton"
{
	"ControlName"	"EditablePanel"
	"fieldname"		"MutePlayersButton"
	"xpos"			"0"
	"ypos"			"0"//175"
	"zpos"			"12"
	"wide"			"60"
	"tall"			"60"
	"visible"		"1"
	"navDown"			"CallVoteButton"
	"navUp"		"ChangeServerButton"
	"navToRelay"	"SubButton"
	
	"pin_to_sibling" 							"CallVoteButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	
	"SubButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"SubButton"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"f0"
		"tall"			"f0"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"textinsetx"	"0"
		"use_proportional_insets" "1"
		"font"			"m0refont14"
		"textAlignment"	"north-west"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"proportionaltoparent"	"1"
		
		"paintbackground"	"0"
		"paintborder"		"1"	
		"defaultFgColor_override" "175 175 175 255"
		"armedFgColor_override" "G_Highlight"
		"depressedFgColor_override" "G_Highlight"
		"image_drawcolor" "175 175 175 255"
		"image_armedcolor" "G_Highlight"
		
		"SubImage"
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "10"
			"ypos" "10"
			"zpos" "1"
			"wide" "40"
			"tall" "40"
			"visible" "1"
			"enabled" "1"
			"image" "icon_checkbox"
			"scaleImage" "1"
		}				
	}
}


// pause menu element
// replaces old change server position
"CallVoteButton" 
{
	"ControlName" "EditablePanel"
	"fieldname" "CallVoteButton"
	"xpos" "r220"//380"
	"ypos" "r60" //231
	"zpos" "11"
	"wide" "60"
	"tall" "60"
	"visible" "1"
	//"pin_to_sibling" 							"TF2SettingsButton"
	//"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	//"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "0"
		"use_proportional_insets" "1"
		"font" "m0refont14"
		"textAlignment" "north-west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		"defaultFgColor_override" "255 255 255 255"
		"armedFgColor_override" "G_Highlight"
		"depressedFgColor_override" "G_Highlight"
		"image_drawcolor" "175 175 175 255"
		"image_armedcolor" "G_Highlight"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "10"
			"ypos" "10"
			"zpos" "1"
			"wide" "40"
			"tall" "40"
			"visible" "1"
			"enabled" "1"
			"image" "icon_checkbox"
			"scaleImage" "1"
		}
	}
}


"AchievementsButton" 
{
	"ControlName" "CExImageButton"
	"fieldName" "AchievementsButton"
	"xpos" "0"
	"ypos" "4"
	"zpos" "3"
	"wide" "12"
	"tall" "12"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"tabPosition" "0"
	"labelText" ""
	"font" "TF2Glyphs25"
	"textAlignment" "north"
	"dulltext" "0"
	"brighttext" "0"
	"default" "1"
	"Command" "OpenAchievementsDialog"
	"sound_depressed" "UI/buttonclick.wav"
	"sound_released" "UI/buttonclickrelease.wav"
	"border_default" ""
	"border_armed" ""
	"paintbackground" "0"
	"PaintBackgroundType" "0"
	
	"image_drawcolor" "175 175 175 255"
	"image_armedcolor" "G_Highlight"
	
	"defaultFgColor_override" "255 255 255 255"
	"armedFgColor_override" "G_Highlight"
	"depressedFgColor_override" "G_Highlight"

	"pin_to_sibling" 							"GeneralStoreButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_BOTTOMLEFT"
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "0"
		"ypos" "0"
		"zpos" "1"
		"wide" "12"
		"tall" "12"
		"visible" "1"
		"enabled" "1"
		"image" "glyph_achievements"
		"scaleImage" "1"
	}
}

"ReportBugButton" 
{
	"ControlName" "CExImageButton"
	"fieldName" "ReportBugButton"
	"xpos" "4"
	"ypos" "0"
	"zpos" "1"
	"wide" "12"
	"tall" "12"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"tabPosition" "0"
	"labelText" ""
	"font" "TF2Glyphs25"
	"textAlignment" "north"
	"dulltext" "0"
	"brighttext" "0"
	"default" "1"
	"Command" "engine bug"
	"sound_depressed" "UI/buttonclick.wav"
	"sound_released" "UI/buttonclickrelease.wav"
	"border_default" ""
	"border_armed" ""
	"paintbackground" "0"
	"PaintBackgroundType" "0"
	
	"image_drawcolor" "175 175 175 255"
	"image_armedcolor" "G_Highlight"
	
	"defaultFgColor_override" "255 255 255 255"
	"armedFgColor_override" "G_Highlight"
	"depressedFgColor_override" "G_Highlight"
	
	"pin_to_sibling" 							"AchievementsButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "0"
		"ypos" "0"
		"zpos" "1"
		"wide" "12"
		"tall" "12"
		"visible" "1"
		"enabled" "1"
		"image" "glyph_bug"
		"scaleImage" "1"
	}
}
"SettingsButton" 
{
	"ControlName" "CExImageButton"
	"fieldName" "SettingsButton"
	"xpos" "0"
	"ypos" "0"//237"//161
	"zpos" "1"
	"wide" "60"
	"tall" "60"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"tabPosition" "0"
	"labelText" ""//#GameUI_GameMenu_Options"
	"font" "m0refont20"
	"textAlignment" "north-west"
	"textinsetx" "0"
	"use_proportional_insets" "1"
	"dulltext" "0"
	"brighttext" "0"
	"default" "1"
	"Command" "OpenOptionsDialog"
	"sound_depressed" "UI/buttonclick.wav"
	"sound_released" "UI/buttonclickrelease.wav"
	"border_default" ""
	"border_armed" ""
	"paintbackground" "0"
	
	"image_drawcolor" "175 175 175 255"
	"image_armedcolor_override" "G_Highlight"
	
	"defaultFgColor_override" "255 255 255 255"
	"armedFgColor_override" "G_Highlight"
	"depressedFgColor_override" "G_Highlight"
	
	"pin_to_sibling" 							"CharacterSetupButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "10"
		"ypos" "10"
		"zpos" "1"
		"wide" "40"
		"tall" "40"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "glyph_options"
	}
}
"TF2SettingsButton" 
{
	"ControlName" "EditablePanel"
	"fieldname" "TF2SettingsButton"
	"xpos" "0"//10"
	"ypos" "0"//c135"//r55"
	"zpos" "11"
	"wide" "60"
	"tall" "60"
	"visible" "1"
	"PaintBackgroundType" "2"
	
	"pin_to_sibling" 							"SettingsButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	
	"SubButton"
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "5"
		"ypos" "0"//257"
		"zpos" "1"
		"wide" "60"
		"tall" "60"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"labelText" "+"
		"font" "Orbit36"//20"
		"textAlignment" "north-west"
		"textinsetx" "0"//70"
		"textinsety" "-8"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"Command" "opentf2options"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"

		"image_drawcolor" "175 175 175 255"
		"image_armedcolor" "G_Highlight"
		
		"defaultFgColor_override" "175 175 175 255"
		"armedFgColor_override" "255 255 255 255"
		"depressedFgColor_override" "G_Highlight"


		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "5"
			"ypos" "10"
			"zpos" "1"
			"wide" "40"
			"tall" "40"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
			"image" "glyph_options"
		}
	}
}

"QuitButton" 
{
	"ControlName" "CExImageButton"
	"fieldName" "QuitButton"
	"xpos" "9940"
	"ypos" "355"
	"zpos" "1"
	"wide" "12"
	"tall" "12"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"tabPosition" "0"
	"labelText" "Quit"
	"font" "m0refont20"
	"textAlignment" "north-west"
	"textinsetx" "0"
	"use_proportional_insets" "1"
	"dulltext" "0"
	"brighttext" "0"
	"default" "1"
	"Command" "engine replay_confirmquit"
	"sound_depressed" "UI/buttonclick.wav"
	"sound_released" "UI/buttonclickrelease.wav"
	"border_default" ""
	"border_armed" ""
	"paintbackground" "0"
	"defaultFgColor_override" "255 255 255 255"
	"armedFgColor_override" "225 30 30 255"
	"depressedFgColor_override" "225 30 30 255"
	"image_drawcolor" "235 226 202 255"
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "9999"
		"ypos" "9999"
		"zpos" "1"
		"wide" "14"
		"tall" "14"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "glyph_quit"
	}
}
"DisconnectButton" 
{
	"ControlName" "CExImageButton"
	"fieldName" "DisconnectButton"
	"xpos" "9940"
	"ypos" "355"
	"zpos" "1"
	"wide" "140"
	"tall" "20"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"tabPosition" "0"
	"labelText" "#TF_Disconnect"
	"font" "m0refont20"
	"textAlignment" "north-west"
	"textinsetx" "0"
	"use_proportional_insets" "1"
	"dulltext" "0"
	"brighttext" "0"
	"default" "1"
	"Command" "engine disconnect"
	"sound_depressed" "UI/buttonclick.wav"
	"sound_released" "UI/buttonclickrelease.wav"
	"border_default" ""
	"border_armed" ""
	"paintbackground" "0"
	"defaultFgColor_override" "255 255 255 255"
	"armedFgColor_override" "225 30 30 255"
	"depressedFgColor_override" "225 30 30 255"
	"image_drawcolor" "235 226 202 255"
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "9999"
		"ypos" "9999"
		"zpos" "1"
		"wide" "14"
		"tall" "14"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "glyph_quit"
	}
}
"CommandsBG"
{
	"ControlName" "CExLabel"
	"fieldName" "CommandsBG"
	"xpos" "0"
	"ypos" "5"
	"zpos" "-10"
	"wide" "150"
	"tall" "64" //50
	"bgcolor_override" "panelBGtransparent"
	"labelText" ""
	"visible" "1"
	"pin_to_sibling" 							"FriendsContainer"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_BOTTOMLEFT"
}
"RecordFixButton"
{
	"ControlName" "EditablePanel"
	"fieldname" "RecordFixButton"
	"xpos" "0"
	"ypos" "0"//r55"
	"zpos" "11"
	"wide" "60"
	"tall" "14"
	"visible" "1"
	"pin_to_sibling" 							"DemoUIButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_BOTTOMLEFT"
	"PaintBackgroundType" "2"
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "0"
		"use_proportional_insets" "1"
		"font" "m0refont14"
		"textAlignment" "north-west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		"defaultFgColor_override" "255 255 255 255"
		"armedFgColor_override" "G_Highlight_text"
		"depressedFgColor_override" "G_Highlight_text"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "235 226 202 255"
		
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "9999"
			"ypos" "9999"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
		}
	}
}
"StopRecordButton" 
{
	"ControlName" "EditablePanel"
	"fieldname" "StopRecordButton"
	"xpos" "0"
	"ypos" "0"
	"zpos" "12"
	"wide" "50"
	"tall" "14"
	"visible" "1"
	"PaintBackgroundType" "2"
	"pin_to_sibling" 							"RecordFixButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "15"
		"use_proportional_insets" "1"
		"font" "m0refont14"
		"textAlignment" "north-west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		"defaultFgColor_override" "255 255 255 255"
		"armedFgColor_override" "G_Highlight_text"
		"depressedFgColor_override" "G_Highlight_text"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "235 226 202 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "9999"
			"ypos" "9999"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
		}
	}
}
"DemoUIButton" 
{
	"ControlName" "EditablePanel"
	"fieldname" "DemoUIButton"
	"xpos" "0"
	"ypos" "0"
	"zpos" "11"
	"wide" "100"
	"tall" "14"
	"visible" "1"
	"PaintBackgroundType" "2"
	"pin_to_sibling" 							"ReloadHUDButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_BOTTOMLEFT"
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "0"
		"use_proportional_insets" "1"
		"font" "m0refont14"
		"textAlignment" "north-west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		"defaultFgColor_override" "255 255 255 255"
		"armedFgColor_override" "G_Highlight_text"
		"depressedFgColor_override" "G_Highlight_text"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "235 226 202 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "9999"
			"ypos" "9999"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
		}
	}
}
"ReloadHUDButton" 
{
	"ControlName" "EditablePanel"
	"fieldname" "ReloadHUDButton"
	"xpos" "0"
	"ypos" "0"
	"zpos" "11"
	"wide" "100"
	"tall" "14"
	"visible" "1"
	"PaintBackgroundType" "2"
	"pin_to_sibling" 							"MinmodeButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_BOTTOMLEFT"
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "0"
		"use_proportional_insets" "1"
		"font" "m0refont14"
		"textAlignment" "north-west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		"defaultFgColor_override" "255 255 255 255"
		"armedFgColor_override" "G_Highlight_text"
		"depressedFgColor_override" "G_Highlight_text"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "235 226 202 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "9999"
			"ypos" "9999"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
		}
	}
}
"MinmodeButton" 
{
	"ControlName" "EditablePanel"
	"fieldname" "MinmodeButton"
	"xpos" "-10"
	"ypos" "-5"//301"
	"zpos" "11"
	"wide" "100"
	"tall" "14"
	"visible" "1"
	"PaintBackgroundType" "2"
	"pin_to_sibling" 							"CommandsBG"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPLEFT"
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "480"
		"autoResize" "0"
		"pinCorner" "3"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "0"
		"use_proportional_insets" "1"
		"font" "m0refont14"
		"textAlignment" "north-west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"border_default" ""
		"border_armed" ""
		"paintbackground" "0"
		"defaultFgColor_override" "255 255 255 255"
		"armedFgColor_override" "G_Highlight_text"
		"depressedFgColor_override" "G_Highlight_text"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "235 226 202 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "9999"
			"ypos" "9999"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"scaleImage" "1"
		}
	}
}

"BackToReplaysButton" 
{
	"ControlName" "CExImageButton"
	"fieldName" "BackToReplaysButton"
	"xpos" "0"
	"ypos" "0"
	"zpos" "1"
	"wide" "0"
	"tall" "0"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "0"
	"enabled" "1"
	"tabPosition" "0"
	"labelText" "#GameUI_GameMenu_ExitReplay"
	"font" "HudFontSmallBold"
	"textAlignment" "north-west"
	"textinsetx" "35"
	"use_proportional_insets" "1"
	"dulltext" "0"
	"brighttext" "0"
	"default" "1"
	"Command" "exitreplayeditor"
	"sound_depressed" "UI/buttonclick.wav"
	"sound_released" "UI/buttonclickrelease.wav"
	"image_drawcolor" "255 255 255 255"
	"image_armedcolor" "G_Highlight"
	
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "16"
		"ypos" "6"
		"zpos" "1"
		"wide" "14"
		"tall" "14"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "glyph_quit"
	}
	
}

// Contracker
"QuestLogButton" 
{
	"ControlName" "EditablePanel"
	"fieldName" "QuestLogButton"
	"xpos" "4"
	"ypos" "0"
	"zpos" "1"
	"wide" "12"
	"tall" "12"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"tabPosition" "0"
	"navUp" "Notifications_Panel"
	"navLeft" "SettingsButton"
	
	"image_drawcolor" "175 175 175 255"
	"image_armedcolor" "G_Highlight"
	
	"defaultFgColor_override" "255 255 255 255"
	"armedFgColor_override" "G_Highlight"
	"depressedFgColor_override" "G_Highlight"
	
	"pin_to_sibling" 							"ReportBugButton"
	"pin_corner_to_sibling" 					"PIN_TOPLEFT"
	"pin_to_sibling_corner" 					"PIN_TOPRIGHT"
	
	"SubButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "SubButton"
		"xpos" "0"
		"ypos" "0"
		"wide" "f0"
		"tall" "f0"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"textinsetx" "25"
		"labelText" ""
		"use_proportional_insets" "1"
		"font" "HudFontSmallBold"
		"command" "questlog"
		"textAlignment" "west"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"actionsignallevel" "2"
		"proportionaltoparent" "1"
		"paintbackground" "0"
		"paintborder" "0"
		"image_drawcolor" "175 175 175 255"
		"image_armedcolor" "255 255 255 255"
		"SubImage" 
		{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "0"
		"ypos" "0"
		"zpos" "1"
		"wide" "12"
		"tall" "12"
		"visible" "1"
		"enabled" "1"
		"scaleImage" "1"
		"image" "replay/thumbnails/buttons/button_quests_pda"
		"proportionaltoparent" "1"
		"mouseinputenabled" "0"
		"keyboardinputenabled" "0"
		}
	}
}

// Notification button
"Notifications_ShowButtonPanel" 
{
	"ControlName" "EditablePanel"
	"fieldName" "Notifications_ShowButtonPanel"
	"xpos" "r95"
	"ypos" "r46"
	"zpos" "10"
	"wide" "32"
	"tall" "32"
	"autoResize" "0"
	"pinCorner" "3"
	"visible" "1"
	"enabled" "1"
	"SubImage" 
	{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "16"
		"ypos" "0"
		"zpos" "3"
		"wide" "16"
		"tall" "16"
		"visible" "1"
		"enabled" "1"
		"image" "replay/thumbnails/circle_red"
		"scaleImage" "1"
		//"drawcolor" "210 125 33 255"
	}
	"Notifications_CountLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "Notifications_CountLabel"
		"font" "HudFontSmallestBold"
		"labelText" "%noticount%"
		"textAlignment" "center"
		"xpos" "16"
		"ypos" "0"
		"zpos" "4"
		"wide" "16"
		"tall" "16"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"fgcolor_override" "255 255 255 255"
	}
	"Notifications_ShowButtonPanel_SB" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "Notifications_ShowButtonPanel_SB"
		"xpos" "0"
		"ypos" "0"
		"zpos" "1"
		"wide" "32"
		"tall" "32"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"labelText" ""
		"font" "HudFontSmallestBold"
		"textAlignment" "north"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"actionsignallevel" "2"
		"Command" "noti_show"
		"navActivate" "u003CQuickplayButton"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"paintbackground" "0"
		"image_drawcolor" "175 175 175 255"
		"image_armedcolor" "255 255 255 255"
		"SubImage" 
		{
		"ControlName" "ImagePanel"
		"fieldName" "SubImage"
		"xpos" "0"
		"ypos" "0"
		"zpos" "-1"
		"wide" "32"
		"tall" "32"
		"visible" "1"
		"enabled" "1"
		"fillcolor" "0 0 0 0"
		"border" ""
		"image" "replay/thumbnails/buttons/alert"
		"scaleImage" "1"
		}
	}
}
"Notifications_Panel" 
{
	"ControlName" "EditablePanel"
	"fieldName" "Notifications_Panel"
	"xpos" "r210"
	"ypos" "r140"
	"zpos" "10"
	"wide" "210"
	"tall" "80"
	"visible" "0"
	"PaintBackgroundType" "2"
	"paintbackground" "0"
	"border" ""
	"bgcolor_override" "255 255 255 255"
	"Notifications_CloseButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "Notifications_CloseButton"
		"xpos" "186"
		"ypos" "8"
		"zpos" "10"
		"wide" "14"
		"tall" "14"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"labeltext" ""
		"font" "HudFontSmallBold"
		"textAlignment" "north"
		"dulltext" "0"
		"brighttext" "0"
		"default" "0"
		"Command" "noti_hide"
		"actionsignallevel" "2"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"paintbackground" "0"
		"defaultFgColor_override" "50 50 50 255"
		"armedFgColor_override" "G_Highlight"
		"depressedFgColor_override" "50 50 50 255"
		"image_drawcolor" "107 107 107 255"
		"image_armedcolor" "G_Highlight"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "0"
			"ypos" "0"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"image" "close_button"
			"scaleImage" "1"
		}
	}
	"Notifications_TitleLabel" 
	{
	"ControlName" "CExLabel"
	"fieldName" "Notifications_TitleLabel"
	"font" "HudFontSmallBold"
	"labelText" "%notititle%"
	"textAlignment" "north-west"
	"xpos" "12"
	"ypos" "8"
	"wide" "250"
	"tall" "20"
	"autoResize" "0"
	"pinCorner" "0"
	"visible" "1"
	"enabled" "1"
	"fgcolor_override" "White"
	"wrap" "1"
	}
	"Notifications_Scroller" 
	{
	"ControlName" "ScrollableEditablePanel"
	"fieldName" "Notifications_Scroller"
	"xpos" "8"
	"ypos" "25"
	"wide" "210"
	"tall" "135"
	"PaintBackgroundType" "2"
	"fgcolor_override" "White"
		"Notifications_Control" 
		{
		"ControlName" "CMainMenuNotificationsControl"
		"fieldName" "Notifications_Control"
		"xpos" "0"
		"ypos" "0"
		"wide" "220"
		"tall" "135"
		"visible" "1"
		}
	}
}


//////////////////////////////////////////////////////////////
//
// IDK WHAT THESE HIGHLIGHTS ARE
//
//////////////////////////////////////////////////////////////



"TutorialHighlight" 
{
	"ControlName" "CExplanationPopup"
	"fieldName" "TutorialHighlight"
	"xpos" "c-285"
	"ypos" "195"
	"zpos" "100"
	"wide" "250"
	"tall" "120"
	"visible" "0"
	"PaintBackgroundType" "2"
	"paintbackground" "0"
	"border" "MainMenuHighlightBorder"
	"start_x" "c-85"
	"start_y" "185"
	"start_wide" "1"
	"start_tall" "1"
	"end_x" "c20"
	"end_y" "120"
	"end_wide" "250"
	"end_tall" "120"
	"callout_inparents_x" "c-40"
	"callout_inparents_y" "195"
	"TitleLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TitleLabel"
		"font" "HudFontSmallBold"
		"labelText" "%highlighttext%"
		"textAlignment" "north"
		"xpos" "20"
		"ypos" "10"
		"wide" "210"
		"tall" "60"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"wrap" "1"
		"fgcolor_override" "46 43 42 255"
	}
	"TextLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TextLabel"
		"font" "HudFontSmall"
		"labelText" "#MMenu_TutorialHighlight_Text"
		"textAlignment" "south-west"
		"xpos" "20"
		"ypos" "60"
		"wide" "210"
		"tall" "20"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"fgcolor_override" "46 43 42 255"
	}
	"TutorialHighlightButton" 
	{
		"ControlName" "EditablePanel"
		"fieldname" "TutorialHighlightButton"
		"xpos" "10"
		"ypos" "85"
		"wide" "230"
		"tall" "26"
		"visible" "1"
		"SubButton" 
		{
			"ControlName" "CExImageButton"
			"fieldName" "SubButton"
			"xpos" "0"
			"ypos" "0"
			"wide" "230"
			"tall" "26"
			"autoResize" "0"
			"pinCorner" "3"
			"visible" "1"
			"enabled" "1"
			"tabPosition" "0"
			"labeltext" "#MMenu_TutorialHighlight_Button"
			"font" "HudFontSmallBold"
			"textAlignment" "north"
			"dulltext" "0"
			"brighttext" "0"
			"default" "1"
			"sound_depressed" "UI/buttonclick.wav"
			"sound_released" "UI/buttonclickrelease.wav"
			"Command" "tutorial"
			"border_default" "MainMenuButtonDefault"
			"border_armed" "MainMenuButtonArmed"
			"paintbackground" "0"
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			"image_drawcolor" "117 107 94 255"
			"image_armedcolor" "235 226 202 255"
			"SubImage" 
			{
				"ControlName" "ImagePanel"
				"fieldName" "SubImage"
				"xpos" "6"
				"ypos" "6"
				"zpos" "1"
				"wide" "14"
				"tall" "14"
				"visible" "1"
				"enabled" "1"
				"scaleImage" "1"
			}
		}
	}
	"CloseButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "CloseButton"
		"xpos" "230"
		"ypos" "5"
		"zpos" "10"
		"wide" "14"
		"tall" "14"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"labeltext" ""
		"font" "HudFontSmallBold"
		"textAlignment" "north"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"Command" "close"
		"paintbackground" "0"
		"defaultFgColor_override" "46 43 42 255"
		"armedFgColor_override" "235 226 202 255"
		"depressedFgColor_override" "46 43 42 255"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "200 80 60 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "0"
			"ypos" "0"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"image" "close_button"
			"scaleImage" "1"
		}
	}
}
"PracticeHighlight" 
{
	"ControlName" "CExplanationPopup"
	"fieldName" "PracticeHighlight"
	"zpos" "100"
	"wide" "250"
	"tall" "120"
	"visible" "0"
	"PaintBackgroundType" "2"
	"paintbackground" "0"
	"border" "MainMenuHighlightBorder"
	"start_x" "c-85"
	"start_y" "185"
	"start_wide" "1"
	"start_tall" "1"
	"end_x" "c20"
	"end_y" "120"
	"end_wide" "250"
	"end_tall" "120"
	"callout_inparents_x" "c-40"
	"callout_inparents_y" "195"
	"TitleLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TitleLabel"
		"font" "HudFontSmallBold"
		"labelText" "#MMenu_PracticeHighlight_Title"
		"textAlignment" "north"
		"xpos" "20"
		"ypos" "10"
		"wide" "210"
		"tall" "50"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"wrap" "1"
		"fgcolor_override" "46 43 42 255"
	}
	"TextLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TextLabel"
		"font" "HudFontSmall"
		"labelText" "#MMenu_PracticeHighlight_Text"
		"textAlignment" "south-west"
		"xpos" "20"
		"ypos" "50"
		"wide" "210"
		"tall" "30"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"fgcolor_override" "46 43 42 255"
	}
	"PracticeHighlightButton" 
	{
		"ControlName" "EditablePanel"
		"fieldname" "PracticeHighlightButton"
		"xpos" "10"
		"ypos" "85"
		"wide" "230"
		"tall" "26"
		"visible" "1"
		"SubButton" 
		{
			"ControlName" "CExImageButton"
			"fieldName" "SubButton"
			"xpos" "0"
			"ypos" "0"
			"wide" "230"
			"tall" "26"
			"autoResize" "0"
			"pinCorner" "3"
			"visible" "1"
			"enabled" "1"
			"tabPosition" "0"
			"labeltext" "#MMenu_PracticeHighlight_Button"
			"font" "HudFontSmallBold"
			"textAlignment" "north"
			"dulltext" "0"
			"brighttext" "0"
			"default" "1"
			"sound_depressed" "UI/buttonclick.wav"
			"sound_released" "UI/buttonclickrelease.wav"
			"Command" "offlinepractice"
			"border_default" "MainMenuButtonDefault"
			"border_armed" "MainMenuButtonArmed"
			"paintbackground" "0"
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "235 226 202 255"
			"depressedFgColor_override" "46 43 42 255"
			"image_drawcolor" "117 107 94 255"
			"image_armedcolor" "235 226 202 255"
			"SubImage" 
			{
				"ControlName" "ImagePanel"
				"fieldName" "SubImage"
				"xpos" "6"
				"ypos" "6"
				"zpos" "1"
				"wide" "14"
				"tall" "14"
				"visible" "1"
				"enabled" "1"
				"scaleImage" "1"
			}
		}
	}
	"CloseButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "CloseButton"
		"xpos" "230"
		"ypos" "5"
		"zpos" "10"
		"wide" "14"
		"tall" "14"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"labeltext" ""
		"font" "HudFontSmallBold"
		"textAlignment" "north"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"Command" "close"
		"paintbackground" "0"
		"defaultFgColor_override" "46 43 42 255"
		"armedFgColor_override" "235 226 202 255"
		"depressedFgColor_override" "46 43 42 255"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "200 80 60 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "0"
			"ypos" "0"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"image" "close_button"
			"scaleImage" "1"
		}
	}
}

"OptionsHighlightPanel" 
{
	"ControlName" "CExplanationPopup"
	"fieldName" "OptionsHighlightPanel"
	"xpos" "c-55"
	"ypos" "280"
	"zpos" "100"
	"wide" "250"
	"tall" "120"
	"visible" "0"
	"PaintBackgroundType" "2"
	"paintbackground" "0"
	"border" "MainMenuHighlightBorder"
	"start_x" "c238"
	"start_y" "437"
	"start_wide" "1"
	"start_tall" "1"
	"end_x" "c55"
	"end_y" "280"
	"end_wide" "250"
	"end_tall" "120"
	"callout_inparents_x" "c240"
	"callout_inparents_y" "437"
	"TitleLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TitleLabel"
		"font" "HudFontSmallBold"
		"labelText" "#MMenu_OptionsHighlightPanel_Title"
		"textAlignment" "north-west"
		"xpos" "10"
		"ypos" "10"
		"wide" "210"
		"tall" "20"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"wrap" "1"
		"fgcolor_override" "46 43 42 255"
	}
	"TextLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TextLabel"
		"font" "HudFontSmall"
		"labelText" "#MMenu_OptionsHighlightPanel_Text"
		"textAlignment" "north-west"
		"xpos" "20"
		"ypos" "30"
		"wide" "210"
		"tall" "90"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"wrap" "1"
		"fgcolor_override" "46 43 42 255"
	}
	"CloseButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "CloseButton"
		"xpos" "230"
		"ypos" "5"
		"zpos" "10"
		"wide" "14"
		"tall" "14"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"labeltext" ""
		"font" "HudFontSmallBold"
		"textAlignment" "north"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"Command" "close"
		"paintbackground" "0"
		"defaultFgColor_override" "46 43 42 255"
		"armedFgColor_override" "235 226 202 255"
		"depressedFgColor_override" "46 43 42 255"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "200 80 60 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "0"
			"ypos" "0"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"image" "close_button"
			"scaleImage" "1"
		}
	}
}
"LoadoutHighlightPanel" 
{
	"ControlName" "CExplanationPopup"
	"fieldName" "LoadoutHighlightPanel"
	"xpos" "c-55"
	"ypos" "280"
	"zpos" "100"
	"wide" "250"
	"tall" "120"
	"visible" "0"
	"PaintBackgroundType" "2"
	"paintbackground" "0"
	"border" "MainMenuHighlightBorder"
	"start_x" "c-190"
	"start_y" "267"
	"start_wide" "1"
	"start_tall" "1"
	"end_x" "c-125"
	"end_y" "180"
	"end_wide" "250"
	"end_tall" "220"
	"callout_inparents_x" "c-163"
	"callout_inparents_y" "267"
	"TitleLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TitleLabel"
		"font" "HudFontSmallBold"
		"labelText" "#MMenu_LoadoutHighlightPanel_Title"
		"textAlignment" "north-west"
		"xpos" "10"
		"ypos" "10"
		"wide" "210"
		"tall" "20"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"wrap" "1"
		"fgcolor_override" "46 43 42 255"
	}
	"TextLabel" 
	{
		"ControlName" "CExLabel"
		"fieldName" "TextLabel"
		"font" "HudFontSmall"
		"labelText" "#MMenu_LoadoutHighlightPanel_Text"
		"textAlignment" "north-west"
		"xpos" "20"
		"ypos" "30"
		"wide" "210"
		"tall" "190"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"wrap" "1"
		"fgcolor_override" "46 43 42 255"
	}
	"CloseButton" 
	{
		"ControlName" "CExImageButton"
		"fieldName" "CloseButton"
		"xpos" "230"
		"ypos" "5"
		"zpos" "10"
		"wide" "14"
		"tall" "14"
		"autoResize" "0"
		"pinCorner" "0"
		"visible" "1"
		"enabled" "1"
		"tabPosition" "0"
		"labeltext" ""
		"font" "HudFontSmallBold"
		"textAlignment" "north"
		"dulltext" "0"
		"brighttext" "0"
		"default" "1"
		"sound_depressed" "UI/buttonclick.wav"
		"sound_released" "UI/buttonclickrelease.wav"
		"Command" "close"
		"paintbackground" "0"
		"defaultFgColor_override" "46 43 42 255"
		"armedFgColor_override" "235 226 202 255"
		"depressedFgColor_override" "46 43 42 255"
		"image_drawcolor" "117 107 94 255"
		"image_armedcolor" "200 80 60 255"
		"SubImage" 
		{
			"ControlName" "ImagePanel"
			"fieldName" "SubImage"
			"xpos" "0"
			"ypos" "0"
			"zpos" "1"
			"wide" "14"
			"tall" "14"
			"visible" "1"
			"enabled" "1"
			"image" "close_button"
			"scaleImage" "1"
		}
	}
}


//////////////////////////////////////////////////////////////
//
// UNUSED
//
//////////////////////////////////////////////////////////////


"StoreHighlightPanel" 
{
"ControlName" "CExplanationPopup"
"fieldName" "StoreHighlightPanel"
"xpos" "c0"
"ypos" "300"
"zpos" "100"
"wide" "250"
"tall" "60"
"visible" "0"
"PaintBackgroundType" "2"
"paintbackground" "0"
"border" "MainMenuHighlightBorder"
"start_x" "c20"
"start_y" "285"
"start_wide" "250"
"start_tall" "125"
"end_x" "c20"
"end_y" "285"
"end_wide" "250"
"end_tall" "125"
"callout_inparents_x" "c-40"
"callout_inparents_y" "267"
"TitleLabel" 
{
"ControlName" "CExLabel"
"fieldName" "TitleLabel"
"font" "HudFontSmallBold"
"labelText" "#MMenu_StoreHighlightPanel_Title"
"textAlignment" "north-west"
"xpos" "10"
"ypos" "10"
"wide" "210"
"tall" "20"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"wrap" "1"
"fgcolor_override" "46 43 42 255"
}
"TextLabel" 
{
"ControlName" "CExLabel"
"fieldName" "TextLabel"
"font" "HudFontSmall"
"labelText" "%highlighttext%"
"textAlignment" "north-west"
"xpos" "20"
"ypos" "30"
"wide" "210"
"tall" "190"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"wrap" "1"
"fgcolor_override" "46 43 42 255"
}
"CloseButton" 
{
"ControlName" "CExImageButton"
"fieldName" "CloseButton"
"xpos" "230"
"ypos" "5"
"zpos" "10"
"wide" "14"
"tall" "14"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labeltext" ""
"font" "HudFontSmallBold"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"Command" "close"
"paintbackground" "0"
"defaultFgColor_override" "46 43 42 255"
"armedFgColor_override" "235 226 202 255"
"depressedFgColor_override" "46 43 42 255"
"image_drawcolor" "117 107 94 255"
"image_armedcolor" "200 80 60 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "14"
"tall" "14"
"visible" "1"
"enabled" "1"
"image" "close_button"
"scaleImage" "1"
}
}
}

"JungleInfernoImage" 
{
"ControlName" "ImagePanel"
"fieldName" "JungleInfernoImage"
"xpos" "c170"
"ypos" "64"
"zpos" "1"
"wide" "o4"
"tall" "32"
"visible" "0"
"enabled" "1"
"image" "../logo/inferno_logo_anim"
"scaleImage" "1"
"mouseinputenabled" "0"
"if_operation" 
{
"visible" "1"
}
}
"TFCharacterImage" 
{
"ControlName" "ImagePanel"
"fieldName" "TFCharacterImage"
"xpos" "c-9250"
"ypos" "-80"
"zpos" "-99"
"wide" "600"
"tall" "600"
"visible" "0"
"enabled" "1"
"scaleImage" "1"
"if_operation" 
{
"image" "../console/title_team_jungle_inferno_2017_widescreen"
}
}
"PlayLabel" 
{
"ControlName" "CExLabel"
"fieldName" "PlayLabel"
"font" "HudFontSmallBold"
"labelText" "#MMenu_Play"
"textAlignment" "north-west"
"xpos" "9999"
"ypos" "9999"
"wide" "140"
"tall" "30"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"fgcolor_override" "235 227 203 255"
}
"CreateServerButton" 
{
"ControlName" "EditablePanel"
"fieldname" "CreateServerButton"
"xpos" "40"
"ypos" "245"
"zpos" "11"
"wide" "0"//100"
"tall" "14"
"visible" "1"
"SubButton" 
{
"ControlName" "CExImageButton"
"fieldName" "SubButton"
"xpos" "0"
"ypos" "0"
"wide" "f0"
"tall" "480"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"textinsetx" "0"
"use_proportional_insets" "1"
"font" "m0refont14"
"textAlignment" "north-west"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"border_default" ""
"border_armed" ""
"paintbackground" "0"
"defaultFgColor_override" "255 255 255 255"
"armedFgColor_override" "G_Highlight"
"depressedFgColor_override" "G_Highlight"
"image_drawcolor" "235 226 202 255"
"image_armedcolor" "235 226 202 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "9999"
"ypos" "9999"
"zpos" "1"
"wide" "12"
"tall" "12"
"visible" "1"
"enabled" "1"
"image" "glyph_create"
"scaleImage" "1"
}
}
}
"WatchStreamButton"
{
"ControlName" "EditablePanel"
"fieldName" "WatchStreamButton"
"xpos" "c9188"
"ypos" "28"
"zpos" "1"
"wide" "32"
"tall" "32"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"navUp" "Notifications_Panel"
"navLeft" "SettingsButton"
"SubButton" 
{
"ControlName" "CExImageButton"
"fieldName" "SubButton"
"xpos" "0"
"ypos" "0"
"wide" "f0"
"tall" "f0"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"textinsetx" "25"
"labelText" ""
"use_proportional_insets" "1"
"font" "HudFontSmallBold"
"command" "watch_stream"
"textAlignment" "west"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"actionsignallevel" "2"
"proportionaltoparent" "1"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"paintbackground" "0"
"paintborder" "0"
"image_drawcolor" "235 226 202 255"
"image_armedcolor" "255 255 255 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "cs-0.5"
"ypos" "cs-0.5"
"zpos" "1"
"wide" "f0"
"tall" "f0"
"visible" "1"
"enabled" "1"
"scaleImage" "1"
"image" "button_streaming"
"proportionaltoparent" "1"
"mouseinputenabled" "0"
"keyboardinputenabled" "0"
}
}
}
"StreamListPanel" 
{
"ControlName" "CTFStreamListPanel"
"fieldName" "StreamListPanel"
"xpos" "c5"
"ypos" "65"
"zpos" "1"
"wide" "300"
"tall" "350"
"visible" "0"
"PaintBackgroundType" "2"
"paintbackground" "0"
"border" "MainMenuHighlightBorder"
"navDown" "SettingsButton"
"navLeft" "WatchStreamButton"
}

// MOTD STUFF

"MOTD_ShowButtonPanel" 
{
"ControlName" "EditablePanel"
"fieldName" "MOTD_ShowButtonPanel"
"xpos" "c9268"
"ypos" "28"
"zpos" "1"
"wide" "32"
"tall" "32"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"MOTD_ShowButtonPanel_SB" 
{
"ControlName" "CExImageButton"
"fieldName" "MOTD_ShowButtonPanel_SB"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "32"
"tall" "32"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labelText" ""
"font" "HudFontSmallestBold"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"Command" "motd_show"
"actionsignallevel" "2"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"paintbackground" "0"
"image_drawcolor" "235 226 202 255"
"image_armedcolor" "255 255 255 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "32"
"tall" "32"
"visible" "1"
"enabled" "1"
"image" "button_MOTD"
"scaleImage" "1"
}
}
}
"MOTD_Panel" 
{
"ControlName" "EditablePanel"
"fieldName" "MOTD_Panel"
"xpos" "c9990"
"ypos" "9970"//28
"zpos" "1"
"wide" "300"
"tall" "360"
"visible" "0"
"PaintBackgroundType" "2"
"paintbackground" "0"
"border" "MainMenuHighlightBorder"
"MOTD_HeaderContainer" 
{
"ControlName" "EditablePanel"
"fieldName" "MOTD_HeaderContainer"
"xpos" "0"
"ypos" "0"
"wide" "300"
"tall" "22"
"visible" "1"
"MOTD_HeaderLabel" 
{
"ControlName" "CExLabel"
"fieldName" "MOTD_HeaderLabel"
"font" "HudFontSmallBold"
"textAlignment" "north"
"labelText" "%motdheader%"
"xpos" "0"
"ypos" "0"
"wide" "300"
"tall" "24"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"PaintBackgroundType" "2"
"fgcolor_override" "235 226 202 255"
"bgcolor_override" "141 178 61 255"
}
}
"MOTD_CloseButton" 
{
"ControlName" "CExImageButton"
"fieldName" "MOTD_CloseButton"
"xpos" "282"
"ypos" "4"
"zpos" "10"
"wide" "14"
"tall" "14"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labeltext" ""
"font" "HudFontSmallBold"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "0"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"Command" "motd_hide"
"actionsignallevel" "2"
"paintbackground" "0"
"defaultFgColor_override" "46 43 42 255"
"armedFgColor_override" "235 226 202 255"
"depressedFgColor_override" "46 43 42 255"
"image_drawcolor" "235 226 202 255"
"image_armedcolor" "200 80 60 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "14"
"tall" "14"
"visible" "1"
"enabled" "1"
"image" "close_button"
"scaleImage" "1"
}
}
"MOTD_HeaderIcon" 
{
"ControlName" "ImagePanel"
"fieldName" "MOTD_HeaderIcon"
"xpos" "265"
"ypos" "25"
"zpos" "100"
"wide" "25"
"tall" "25"
"visible" "0"
"enabled" "1"
"image" "class_icons/filter_all_motd"
"scaleImage" "1"
}
"MOTD_TitleLabel" 
{
"ControlName" "CExLabel"
"fieldName" "MOTD_TitleLabel"
"font" "HudFontSmallBold"
"labelText" "%motdtitle%"
"textAlignment" "north-west"
"xpos" "10"
"ypos" "25"
"wide" "250"
"tall" "15"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"fgcolor_override" "46 43 42 255"
"wrap" "1"
}
"MOTD_Label" 
{
"ControlName" "CExLabel"
"fieldName" "MOTD_Label"
"font" "HudFontSmall"
"labelText" "%motddate%"
"textAlignment" "north-west"
"xpos" "10"
"ypos" "40"
"wide" "300"
"tall" "15"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"fgcolor_override" "46 43 42 255"
}
"MOTD_TitleImageBg" 
{
"ControlName" "ImagePanel"
"fieldName" "MOTD_TitleImageBg"
"xpos" "10"
"ypos" "55"
"zpos" "99"
"wide" "280"
"tall" "180"
"visible" "1"
"enabled" "1"
"image" "item_bg"
"scaleImage" "1"
}
"MOTD_TitleImageContainer" 
{
"ControlName" "EditablePanel"
"fieldName" "MOTD_TitleImageContainer"
"xpos" "10"
"ypos" "55"
"zpos" "100"
"wide" "280"
"tall" "180"
"visible" "1"
"MOTD_TitleImage" 
{
"ControlName" "ImagePanel"
"fieldName" "MOTD_TitleImage"
"xpos" "0"
"ypos" "0"
"zpos" "100"
"wide" "280"
"tall" "280"
"visible" "1"
"enabled" "1"
"image" "class_icons/filter_all"
"scaleImage" "0"
}
}
"MOTD_TextScroller" 
{
"ControlName" "ScrollableEditablePanel"
"fieldName" "MOTD_TextScroller"
"xpos" "20"
"ypos" "240"
"wide" "280"
"tall" "95"
"PaintBackgroundType" "2"
"fgcolor_override" "117 107 94 255"
"MOTD_TextPanel" 
{
"ControlName" "EditablePanel"
"fieldName" "MOTD_TextPanel"
"xpos" "0"
"ypos" "0"
"wide" "250"
"tall" "300"
"visible" "1"
"PaintBackgroundType" "2"
"MOTD_TextLabel" 
{
"ControlName" "CExLabel"
"fieldName" "MOTD_TextLabel"
"font" "HudFontSmall"
"labelText" "%motdtext%"
"textAlignment" "north-west"
"xpos" "0"
"ypos" "0"
"wide" "250"
"tall" "300"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"fgcolor_override" "46 43 42 255"
"wrap" "1"
}
}
}
"MOTD_URLButton" 
{
"ControlName" "CExButton"
"fieldName" "MOTD_URLButton"
"xpos" "75"
"ypos" "339"
"wide" "150"
"tall" "15"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labelText" "#MMenu_MOTD_URL"
"textinsetx" "20"
"use_proportional_insets" "1"
"font" "HudFontSmallestBold"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"command" "motd_viewurl"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"defaultFgColor_override" "235 226 202 255"
"defaultBgColor_override" "46 43 42 255"
"armedFgColor_override" "235 226 202 255"
"depressedFgColor_override" "235 226 202 255"
}
"MOTD_PrevButton" 
{
"ControlName" "CExImageButton"
"fieldName" "MOTD_PrevButton"
"xpos" "12"
"ypos" "336"
"zpos" "1"
"wide" "20"
"tall" "20"
"autoResize" "0"
"pinCorner" "3"
"visible" "0"
"enabled" "1"
"tabPosition" "0"
"labelText" ""
"font" "HudFontSmallBold"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"Command" "motd_prev"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"paintbackground" "0"
"image_drawcolor" "235 226 202 255"
"image_armedcolor" "255 255 255 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "20"
"tall" "20"
"visible" "1"
"enabled" "1"
"image" "blog_back"
"scaleImage" "1"
}
}
"MOTD_NextButton" 
{
"ControlName" "CExImageButton"
"fieldName" "MOTD_NextButton"
"xpos" "267"
"ypos" "336"
"zpos" "1"
"wide" "20"
"tall" "20"
"autoResize" "0"
"pinCorner" "3"
"visible" "0"
"enabled" "1"
"tabPosition" "0"
"labelText" ""
"font" "HudFontSmallBold"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"Command" "motd_next"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"paintbackground" "0"
"image_drawcolor" "235 226 202 255"
"image_armedcolor" "255 255 255 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "20"
"tall" "20"
"visible" "1"
"enabled" "1"
"image" "blog_forward"
"scaleImage" "1"
}
}
}
"HTMLContainer" 
{
"ControlName" "EditablePanel"
"fieldName" "HTMLContainer"
"xpos" "c0"
"ypos" "92"
"zpos" "1"
"wide" "300"
"tall" "300"
"autoResize" "3"
"pinCorner" "0"
"visible" "0"
"enabled" "1"
"tabPosition" "0"
"border" "MainMenuBGBorder"
"PaintBackgroundType" "2"
"HTMLLabel" 
{
"ControlName" "CExLabel"
"fieldName" "HTMLLabel"
"font" "HudFontSmallestBold"
"labelText" "#MMenu_HTML"
"textAlignment" "north-west"
"xpos" "5"
"ypos" "5"
"wide" "290"
"tall" "15"
"autoResize" "0"
"pinCorner" "0"
"visible" "0"
"enabled" "1"
}
"HTML" 
{
"ControlName" "HTML"
"fieldName" "HTML"
"xpos" "5"
"ypos" "5"
"zpos" "1"
"wide" "290"
"tall" "290"
"autoResize" "3"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
}
}
"TrainingButton" 
{
"ControlName" "EditablePanel"
"fieldname" "TrainingButton"
"xpos" "40"
"ypos" "245"
"zpos" "11"
"wide" "100"
"tall" "14"
"visible" "1"
"PaintBackgroundType" "2"
"SubButton" 
{
"ControlName" "CExImageButton"
"fieldName" "SubButton"
"xpos" "9990"
"ypos" "9990"
"wide" "f0"
"tall" "480"
"autoResize" "0"
"pinCorner" "3"
"visible" "0"
"enabled" "1"
"tabPosition" "0"
"textinsetx" "0"
"use_proportional_insets" "1"
"font" "m0refont14"
"textAlignment" "north-west"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"border_default" ""
"border_armed" ""
"paintbackground" "0"
"defaultFgColor_override" "255 255 255 255"
"armedFgColor_override" "G_Highlight"
"depressedFgColor_override" "G_Highlight"
"image_drawcolor" "117 107 94 255"
"image_armedcolor" "235 226 202 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "9999"
"ypos" "9999"
"zpos" "1"
"wide" "14"
"tall" "14"
"visible" "1"
"enabled" "1"
"scaleImage" "1"
}
}
}
"VRModeButton" 
{
"ControlName" "EditablePanel"
"fieldname" "VRModeButton"
"xpos" "c-285"
"ypos" "379"
"zpos" "11"
"wide" "270"
"tall" "36"
"visible" "1"
"PaintBackgroundType" "2"
"navUp" "ReplayBrowserButton"
"navDown" "QuitButton"
"navRight" "Notifications_ShowButtonPanel"
"navToRelay" "SubButton"
"SubButton" 
{
"ControlName" "CExImageButton"
"fieldName" "SubButton"
"xpos" "0"
"ypos" "0"
"wide" "250"
"tall" "26"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"textinsetx" "25"
"use_proportional_insets" "1"
"font" "HudFontSmallBold"
"textAlignment" "north-west"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"border_default" "MainMenuButtonDefault"
"border_armed" "MainMenuButtonArmed"
"paintbackground" "0"
"defaultFgColor_override" "46 43 42 255"
"armedFgColor_override" "235 226 202 255"
"depressedFgColor_override" "46 43 42 255"
"image_drawcolor" "117 107 94 255"
"image_armedcolor" "235 226 202 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "6"
"ypos" "6"
"zpos" "1"
"wide" "14"
"tall" "14"
"visible" "1"
"enabled" "1"
"scaleImage" "1"
}
}
}

"StoreHasNewItemsImage" 
{
"ControlName" "ImagePanel"
"fieldName" "StoreHasNewItemsImage"
"xpos" "9999"
"ypos" "9999"
"zpos" "13"
"wide" "32"
"tall" "32"
"visible" "0"
"enabled" "1"
"image" "../vgui/new"
"scaleImage" "1"
}

"StoreBGPanel" 
{
"ControlName" "EditablePanel"
"fieldName" "StoreBGPanel"
"xpos" "9999"
"ypos" "9999"
"zpos" "-1"
"wide" "260"
"tall" "60"
"visible" "1"
"PaintBackgroundType" "2"
"border" "MainMenuBGBorder"
}
"CustomizeLabel" 
{
"ControlName" "CExLabel"
"fieldName" "CustomizeLabel"
"font" "HudFontSmallBold"
"labelText" "#MMenu_Customize"
"textAlignment" "north-west"
"xpos" "9999"
"ypos" "9999"
"wide" "140"
"tall" "30"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"fgcolor_override" "235 227 203 255"
}
"CreateBGPanel" 
{
"ControlName" "EditablePanel"
"fieldName" "CreateBGPanel"
"xpos" "9999"
"ypos" "9999"
"zpos" "-1"
"wide" "260"
"tall" "60"
"visible" "1"
"PaintBackgroundType" "2"
"border" "MainMenuBGBorder"
}
"CreateLabel" 
{
"ControlName" "CExLabel"
"fieldName" "CreateLabel"
"font" "HudFontSmallBold"
"labelText" "#MMenu_Create"
"textAlignment" "north-west"
"xpos" "9999"
"ypos" "9999"
"wide" "140"
"tall" "30"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"fgcolor_override" "235 227 203 255"
}
"ShowPromoCodesButton" 
{
"ControlName" "CExImageButton"
"fieldName" "ShowPromoCodesButton"
"xpos" "9999"
"ypos" "9999"
"wide" "250"
"tall" "20"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"font" "HudFontSmallestBold"
"labelText" "#MMenu_ShowPromoCodes"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"command" "showpromocodes"
"border_default" "MainMenuButtonDefault"
"border_armed" "MainMenuButtonArmed"
"paintbackground" "0"
"defaultFgColor_override" "46 43 42 255"
"armedFgColor_override" "235 226 202 255"
"depressedFgColor_override" "46 43 42 255"
}
"FreeTrialPanel" 
{
"ControlName" "EditablePanel"
"fieldName" "FreeTrialPanel"
"xpos" "9999"
"ypos" "9999"
"zpos" "0"
"wide" "250"
"tall" "130"
"visible" "0"
"Image" 
{
"ControlName" "ImagePanel"
"fieldName" "Image"
"xpos" "0"
"ypos" "0"
"zpos" "0"
"wide" "80"
"tall" "80"
"visible" "1"
"enabled" "1"
"image" "tf_box"
"scaleImage" "1"
}
"UpgradeLabel1" 
{
"ControlName" "CExLabel"
"fieldName" "UpgradeLabel"
"font" "HudFontSmallestBold"
"labelText" "#TF_Trial_MainMenu_Upgrade1"
"textAlignment" "north"
"xpos" "80"
"ypos" "5"
"wide" "165"
"tall" "80"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"wrap" "1"
}
"UpgradeLabel2" 
{
"ControlName" "CExLabel"
"fieldName" "UpgradeLabel2"
"font" "HudFontSmallBold"
"labelText" "#TF_Trial_MainMenu_Upgrade2"
"textAlignment" "north"
"xpos" "80"
"ypos" "18"
"wide" "165"
"tall" "80"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"wrap" "1"
"fgcolor" "255 155 138 255"
}
"UpgradeLabel3" 
{
"ControlName" "CExLabel"
"fieldName" "UpgradeLabel3"
"font" "HudFontSmallestBold"
"labelText" "#TF_Trial_MainMenu_Upgrade3"
"textAlignment" "north"
"xpos" "80"
"ypos" "48"
"wide" "165"
"tall" "80"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"wrap" "1"
"fgcolor" "137 134 127 255"
}
}
// who needs a coach anyway?
"RequestCoachButton" 
{
"ControlName" "EditablePanel"
"fieldname" "RequestCoachButton"
"xpos" "9940" //40
"ypos" "245"
"zpos" "11"
"wide" "100"
"tall" "14"
"visible" "1"
"SubButton" 
{
"ControlName" "CExImageButton"
"fieldName" "SubButton"
"xpos" "0"
"ypos" "0"
"wide" "f0"
"tall" "480"
"autoResize" "0"
"pinCorner" "3"
"visible" "0" // 1, hope wont mess up
"enabled" "1"
"tabPosition" "0"
"textinsetx" "0"
"use_proportional_insets" "1"
"font" "m0refont14"
"textAlignment" "north-west"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"border_default" ""
"border_armed" ""
"paintbackground" "0"
"defaultFgColor_override" "255 255 255 255"
"armedFgColor_override" "G_Highlight"
"depressedFgColor_override" "G_Highlight"
"image_drawcolor" "235 226 202 255"
"image_armedcolor" "235 226 202 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "9999"
"ypos" "9999"
"zpos" "1"
"wide" "12"
"tall" "12"
"visible" "1"
"enabled" "1"
"image" "glyph_create"
"scaleImage" "1"
}
}
}
"BackgroundFooter" 
{
"ControlName" "ImagePanel"
"fieldName" "BackgroundFooter"
"xpos" "9999"
"ypos" "9999"
"zpos" "-50"
"wide" "f0"
"tall" "60"
"visible" "1"
"enabled" "1"
"image" "loadout_bottom_gradient"
"tileImage" "1"
}
"FooterLine" 
{
"ControlName" "ImagePanel"
"fieldName" "FooterLine"
"xpos" "9999"
"ypos" "9999"
"zpos" "-5-"
"wide" "f0"
"tall" "10"
"visible" "1"
"enabled" "1"
"image" "loadout_solid_line"
"scaleImage" "1"
}
"NewUserForumsButton" 
{
"ControlName" "CExImageButton"
"fieldName" "NewUserForumsButton"
"xpos" "9940"
"ypos" "428"
"zpos" "2"
"wide" "0"
"tall" "0"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labelText" ""
"font" "TF2Glyphs25"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"Command" "view_newuser_forums"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"border_default" ""
"border_armed" ""
"paintbackground" "0"
"PaintBackgroundType" "0"
"image_drawcolor" "255 255 255 255"
"image_armedcolor" "125 225 30 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "12"
"tall" "12"
"visible" "1"
"enabled" "1"
"image" "glyph_tutorial"
"scaleImage" "1"
}
}
"CommentaryButton" 
{
"ControlName" "CExImageButton"
"fieldName" "CommentaryButton"
"xpos" "9984"
"ypos" "428"
"zpos" "4"
"wide" "0"
"tall" "0"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labelText" ""
"font" "TF2Glyphs24"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"Command" "OpenLoadSingleplayerCommentaryDialog"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"border_default" ""
"border_armed" ""
"paintbackground" "0"
"PaintBackgroundType" "0"
"image_drawcolor" "255 255 255 255"
"image_armedcolor" "125 225 30 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "1"
"zpos" "1"
"wide" "11"
"tall" "11"
"visible" "1"
"enabled" "1"
"image" "glyph_forums"
"scaleImage" "1"
}
}
"CoachPlayersButton" 
{
"ControlName" "CExImageButton"
"fieldName" "CoachPlayersButton"
"xpos" "9106"
"ypos" "428"
"zpos" "5"
"wide" "0"
"tall" "0"
"autoResize" "0"
"pinCorner" "3"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labelText" ""
"font" "TF2Glyphs25"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"Command" "engine cl_coach_toggle"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"border_default" ""
"border_armed" ""
"paintbackground" "0"
"PaintBackgroundType" "0"
"image_drawcolor" "255 255 255 255"
"image_armedcolor" "125 225 30 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "12"
"tall" "12"
"visible" "1"
"enabled" "1"
"image" "glyph_commentary"
"scaleImage" "1"
}
}
"NewUserForumHighlight" 
{
"ControlName" "CExplanationPopup"
"fieldName" "NewUserForumHighlight"
"xpos" "c-55"
"ypos" "280"
"zpos" "100"
"wide" "250"
"tall" "120"
"visible" "0"
"PaintBackgroundType" "2"
"paintbackground" "0"
"border" "MainMenuHighlightBorder"
"start_x" "c-112"
"start_y" "437"
"start_wide" "1"
"start_tall" "1"
"end_x" "c-205"
"end_y" "280"
"end_wide" "250"
"end_tall" "120"
"callout_inparents_x" "c-116"
"callout_inparents_y" "437"
"TitleLabel" 
{
"ControlName" "CExLabel"
"fieldName" "TitleLabel"
"font" "HudFontSmallBold"
"labelText" "#MMenu_NewUserForumHighlight_Title"
"textAlignment" "north-west"
"xpos" "10"
"ypos" "10"
"wide" "210"
"tall" "20"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"wrap" "1"
"fgcolor_override" "46 43 42 255"
}
"TextLabel" 
{
"ControlName" "CExLabel"
"fieldName" "TextLabel"
"font" "HudFontSmall"
"labelText" "#MMenu_NewUserForumHighlight_Text"
"textAlignment" "north-west"
"xpos" "20"
"ypos" "30"
"wide" "210"
"tall" "90"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"wrap" "1"
"fgcolor_override" "46 43 42 255"
}
"CloseButton" 
{
"ControlName" "CExImageButton"
"fieldName" "CloseButton"
"xpos" "230"
"ypos" "5"
"zpos" "10"
"wide" "14"
"tall" "14"
"autoResize" "0"
"pinCorner" "0"
"visible" "1"
"enabled" "1"
"tabPosition" "0"
"labeltext" ""
"font" "HudFontSmallBold"
"textAlignment" "north"
"dulltext" "0"
"brighttext" "0"
"default" "1"
"sound_depressed" "UI/buttonclick.wav"
"sound_released" "UI/buttonclickrelease.wav"
"Command" "close"
"paintbackground" "0"
"defaultFgColor_override" "46 43 42 255"
"armedFgColor_override" "235 226 202 255"
"depressedFgColor_override" "46 43 42 255"
"image_drawcolor" "117 107 94 255"
"image_armedcolor" "200 80 60 255"
"SubImage" 
{
"ControlName" "ImagePanel"
"fieldName" "SubImage"
"xpos" "0"
"ypos" "0"
"zpos" "1"
"wide" "14"
"tall" "14"
"visible" "1"
"enabled" "1"
"image" "close_button"
"scaleImage" "1"
}
}
}


}
